version: '3.4'

services:
  ticketprocessingrestapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:81                          #https://+:443;http://+:80
    ports:
     # - "8080:80"
     # - "8081:443"
       - "9090:81"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  sqlserver:
    volumes:
      - "api_data:/var/opt/mssql"
  #  volumes:
   #   - type: volume
   #     source: ticketprocessingapidbsys
   #     target: /var/opt/sqlserver #/var/opt/mssql/data #/var/opt/sqlserver
   #   - type: volume
   #     source: ticketprocessingapidbusr
    #    target: /var/opt/sqlserver #/var/opt/mssql/data

  elsaserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80  #https://+:443;http://+:80
    ports:
      - "5000:80"
      #- "4041:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
#volumes:
  #ticketprocessingapidbsys:
  #ticketprocessingapidbusr:
volumes: 
  api_data: